import { AssetKeyT } from "../src/hooks/oracle";

/**
 * Converts an asset key into its URL version by changing all '/' to '-'.
 * @param {AssetKeyT} key the asset key
 * @return {string} a url friendly version of the asset key
 */
export function assetKeyToURL(key: AssetKeyT): string {
  return key.replaceAll("/", "-");
}

/**
 * Converts a url back to its asset key version by replacing all '-' with '/'.
 * @param {string} url a url (usually generated by `assetKeyToURL`)
 * @return {AssetKeyT} the original asset key
 */
export function urlToAssetKey(url: string): AssetKeyT {
  return url.replaceAll("-", "/");
}
